# Generated by Django 5.0.4 on 2024-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='platocantidadprecio',
            unique_together={('plato', 'cantidad')},
        ),
    ]
