# Generated by Django 5.0.4 on 2024-04-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0002_alter_plato_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platocantidadprecio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
