# Generated by Django 5.0.4 on 2024-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0003_platocantidadprecio_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroventa',
            old_name='valor_total',
            new_name='total_registro',
        ),
        migrations.AddField(
            model_name='boleta',
            name='total_descuentos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='total_sin_descuento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registroventa',
            name='descuento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroventa',
            name='total_sin_descuento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total_boleta',
            field=models.IntegerField(null=True),
        ),
    ]
