# Generated by Django 5.0.4 on 2024-04-13 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0004_rename_valor_total_registroventa_total_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroVenta',
            new_name='BoletaDetalle',
        ),
        migrations.RenameModel(
            old_name='Boleta',
            new_name='BoletaGeneral',
        ),
    ]
