# Generated by Django 5.0.4 on 2024-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0005_rename_registroventa_boletadetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletageneral',
            name='pagada',
            field=models.BooleanField(default=True),
        ),
    ]
